### ISSUE TITLE
Invalid example in notifications/attachments

### ISSUE THREAD

**Issue by jritsema** [home-assistant/companion.home-assistant#1125]
The [Example Action](https://companion.home-assistant.io/docs/notifications/notification-attachments/#example-action) under `Notifications / Attachments / Standard Attachments / Example action` does not seem to work.

```yaml
automation:
  - alias: Notify Mobile app attachment
    trigger:
      ...
    action:
      - action: notify.mobile_app_<your_device_id_here>
        data:
          message: "Something happened at home!"
          data:
            # an example of an absolute url
            image: "https://www.home-assistant.io/images/default-social.png"
```

When I tried this, I do get the mobile notification, however, I don’t see a thumbnail, and when I expand it, it says, “Failed to load attachment - URLSessionTask failed with error: The internet connection appears to be offline”.

![](https://community-assets.home-assistant.io/original/4X/2/f/6/2f630fd9d9d029f2e198ac34cebfc9921e3c6fb0.jpeg)

It appears that your home assistant server needs to be exposed to the internet, even if you want to only use absolute public URLs to another server.  If this is the case, I would suggest noting this in the documentation as it feels misleading.

Also see https://community.home-assistant.io/t/ios-notifications-with-public-images-on-a-private-server/
