### ISSUE TITLE
Android Notification Docs Importance: vs priority:

### ISSUE THREAD

**Issue by Morphy99** [home-assistant/companion.home-assistant#1182]
I've been struggling to get notifications to show when the screen was locked for a minute or two on my Pixel 9 Pro. I noticed I was using the channel `importance: high` setting instead of the "critical" notification setting of `priority: high`.

IMHO showing a notification when the screen is locked shouldn't be exclusive for critical notifications, maybe the importance setting needs to be referenced in the docs next to [notification channel importance](https://companion.home-assistant.io/docs/notifications/notifications-basic/#notification-channel-importance) as well as in the critical notifications page?

I couldn't see a difference using low/max/min notification channel importance, but that might be a device specific thing? The code I was using:

```
service: notify.mobiles
data:
  message: test
  title: Test Notification
  data:
    car_ui: true
    channel: "Important"
    importance: max
```

**Comment by dshokouhi** [comment]
`priority` is a legacy android setting (before android 8) but also a current firebase setting. it is required for notifications to show up promptly when the device is in doze.  `importance` is for teh channel settings but that does not impact the notification delivery, the critical docs are correct in what they mention.

your yaml does not follow the [critical example](https://companion.home-assistant.io/docs/notifications/critical-notifications#android)

```
service: notify.mobiles
data:
  message: test
  title: Test Notification
  data:
    car_ui: true
    channel: "Important"
    importance: max
    ttl: 0
    priority: high
```

the reason why it is considered a critical notification is because android can rate limit you at any time to delay the speedy notifications so its best to leave that in the hands of the user to determine whats important or not.
