### ISSUE TITLE
Android - Notification via Alarm stream still silent

### ISSUE THREAD

**Issue by BigDoom** [home-assistant/companion.home-assistant#387]
Just updated the app via Google Play to version 3.0.0-full, which should include the change to be able to use the alarm stream for notifications, thus bypass silent mode / do not disturb. Unfortunately when testing it's not working. I only see another channel called 'alarm-stream' that has been added into notifications under the Home Assistant app, but still silent notifications.

My automation in HA: 
```
action:
  -   service: notify.mobile_app_phone
       data:
         message: "Some message"
         title: "Some title"
           data:
             ttl: 0
             priority: high
             channel: alarm_stream
```

This just gives me a silent notification when the action is triggered. When I use my alarm clock on my phone it gives me a sound, so I would assume my alarm notifications are properly set-up on my Android device. Running Android v10.

What am I doing wrong here?
